// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsLHqIIK2uVPL7fS-fC5X-VEjLei7lOqc',
    appId: '1:555454956170:web:e514cf33d581cc1629a373',
    messagingSenderId: '555454956170',
    projectId: 'adaptive-weather-dashboard',
    authDomain: 'adaptive-weather-dashboard.firebaseapp.com',
    storageBucket: 'adaptive-weather-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-WCxd2RfK5_0y8fJYEycuw36BtE0YDU',
    appId: '1:555454956170:android:97eeb8ee13896a6a29a373',
    messagingSenderId: '555454956170',
    projectId: 'adaptive-weather-dashboard',
    storageBucket: 'adaptive-weather-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJtm03VhNZ5LYE3lNAXYH9Zk0OL6W98iI',
    appId: '1:555454956170:ios:f733ea745754a16b29a373',
    messagingSenderId: '555454956170',
    projectId: 'adaptive-weather-dashboard',
    storageBucket: 'adaptive-weather-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.adaptiveWeatherDashboard',
  );

  // Firebase reuses the iOS app config for macOS apps that share the
  // same bundle ID. Manually maintained because the flutterfire CLI
  // hung while parsing the macOS Xcode project — values match `ios`.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJtm03VhNZ5LYE3lNAXYH9Zk0OL6W98iI',
    appId: '1:555454956170:ios:f733ea745754a16b29a373',
    messagingSenderId: '555454956170',
    projectId: 'adaptive-weather-dashboard',
    storageBucket: 'adaptive-weather-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.adaptiveWeatherDashboard',
  );
}
