// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWt58hf4w_opc8VLjWSWEvJEx9f5w0n3U',
    appId: '1:319090660806:web:6a64669779e3978db4cec7',
    messagingSenderId: '319090660806',
    projectId: 'adaptive-weather-dashboard-dev',
    authDomain: 'adaptive-weather-dashboard-dev.firebaseapp.com',
    storageBucket: 'adaptive-weather-dashboard-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACULFCNqIdq1vVm_OIJGPyNBkeMmFwTH4',
    appId: '1:319090660806:android:cc40f9ba94deb660b4cec7',
    messagingSenderId: '319090660806',
    projectId: 'adaptive-weather-dashboard-dev',
    storageBucket: 'adaptive-weather-dashboard-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOAczttrowU-xu_TuxiVbIY443Fan4Qv0',
    appId: '1:319090660806:ios:f72a28ea1296ce8db4cec7',
    messagingSenderId: '319090660806',
    projectId: 'adaptive-weather-dashboard-dev',
    storageBucket: 'adaptive-weather-dashboard-dev.firebasestorage.app',
    iosBundleId: 'com.example.adaptiveWeatherDashboard.dev',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOAczttrowU-xu_TuxiVbIY443Fan4Qv0',
    appId: '1:319090660806:ios:f72a28ea1296ce8db4cec7',
    messagingSenderId: '319090660806',
    projectId: 'adaptive-weather-dashboard-dev',
    storageBucket: 'adaptive-weather-dashboard-dev.firebasestorage.app',
    iosBundleId: 'com.example.adaptiveWeatherDashboard.dev',
  );
}
